// File generated by flutterfire configure
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase options for fast-delivery-32739
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQMojgcMa626RRFJCYJ7r1y9AZ9vn3jPs',
    appId: '1:130528704034:web:2e1e07c4270cb64a947c7b',
    messagingSenderId: '130528704034',
    projectId: 'fast-delivery-32739',
    authDomain: 'fast-delivery-32739.firebaseapp.com',
    storageBucket: 'fast-delivery-32739.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPlmPufMDNBdpgtAfvhiuMVYR-cBAnP8U',
    appId: '1:130528704034:android:e83318c397b8f82e947c7b',
    messagingSenderId: '130528704034',
    projectId: 'fast-delivery-32739',
    storageBucket: 'fast-delivery-32739.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABn5ikJWbNA-NjO6mD5ICd1m9M6BENgU8',
    appId: '1:130528704034:ios:027101810424670f947c7b',
    messagingSenderId: '130528704034',
    projectId: 'fast-delivery-32739',
    authDomain: 'fast-delivery-32739.firebaseapp.com',
    storageBucket: 'fast-delivery-32739.appspot.com',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'fast-delivery-32739',
    authDomain: 'fast-delivery-32739.firebaseapp.com',
    storageBucket: 'fast-delivery-32739.appspot.com',
    iosBundleId: 'com.example.customerApp.RunnerTests',
  );
}
